"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OCSHLib__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "ALLIANCE_LEADER_ROLE",
        outputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "GAME_ADMIN_ROLE",
        outputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
const _bytecode = "0x60d6610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603d5760003560e01c806317282d5c146042578063be22d27d14607a575b600080fd5b60687f828a9190dc16dc0116154c184677dac8abebc0b3aeeba46f3ba5f89b8e41439881565b60405190815260200160405180910390f35b60687f9b7946abd96dccbe6cfc6cc2c13300ab429d93e16fa72dc459eeccda73817f088156fea26469706673582212204d6dace7a6b1f2178f0adaf30ec5e9f28c29cb1da8aa28ddb8f32edf5bde850b64736f6c63430008160033";
const isSuperArgs = (xs) => xs.length > 1;
class OCSHLib__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static bytecode = _bytecode;
    static abi = _abi;
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.OCSHLib__factory = OCSHLib__factory;
