/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { OCSHLib, OCSHLibInterface } from "../../OSCHLib.sol/OCSHLib";

const _abi = [
  {
    inputs: [],
    name: "ALLIANCE_LEADER_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GAME_ADMIN_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60d4610034600b8282823980515f1a60731461002857634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c806317282d5c146040578063be22d27d146078575b5f80fd5b60667f828a9190dc16dc0116154c184677dac8abebc0b3aeeba46f3ba5f89b8e41439881565b60405190815260200160405180910390f35b60667f9b7946abd96dccbe6cfc6cc2c13300ab429d93e16fa72dc459eeccda73817f088156fea26469706673582212206964ff9ef2cbd7e5b4fce3d95fd1fd17f27fbbe3138a647ae94b9ac745379dca64736f6c63430008150033";

type OCSHLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OCSHLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OCSHLib__factory extends ContractFactory {
  constructor(...args: OCSHLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OCSHLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): OCSHLib__factory {
    return super.connect(runner) as OCSHLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OCSHLibInterface {
    return new Interface(_abi) as OCSHLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): OCSHLib {
    return new Contract(address, _abi, runner) as unknown as OCSHLib;
  }
}
