"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Semver__factory = exports.SchemaRegistry__factory = exports.OCSH__factory = exports.ISemver__factory = exports.ISchemaRegistry__factory = exports.IEAS__factory = exports.EAS__factory = exports.BribeEscrow__factory = exports.resolver = exports.eip712 = exports.eip1271 = exports.oschLibSol = exports.identitySbtSol = exports.eligibilitySol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.eligibilitySol = __importStar(require("./Eligibility.sol"));
exports.identitySbtSol = __importStar(require("./IdentitySBT.sol"));
exports.oschLibSol = __importStar(require("./OSCHLib.sol"));
exports.eip1271 = __importStar(require("./eip1271"));
exports.eip712 = __importStar(require("./eip712"));
exports.resolver = __importStar(require("./resolver"));
var BribeEscrow__factory_1 = require("./BribeEscrow__factory");
Object.defineProperty(exports, "BribeEscrow__factory", { enumerable: true, get: function () { return BribeEscrow__factory_1.BribeEscrow__factory; } });
var EAS__factory_1 = require("./EAS__factory");
Object.defineProperty(exports, "EAS__factory", { enumerable: true, get: function () { return EAS__factory_1.EAS__factory; } });
var IEAS__factory_1 = require("./IEAS__factory");
Object.defineProperty(exports, "IEAS__factory", { enumerable: true, get: function () { return IEAS__factory_1.IEAS__factory; } });
var ISchemaRegistry__factory_1 = require("./ISchemaRegistry__factory");
Object.defineProperty(exports, "ISchemaRegistry__factory", { enumerable: true, get: function () { return ISchemaRegistry__factory_1.ISchemaRegistry__factory; } });
var ISemver__factory_1 = require("./ISemver__factory");
Object.defineProperty(exports, "ISemver__factory", { enumerable: true, get: function () { return ISemver__factory_1.ISemver__factory; } });
var OCSH__factory_1 = require("./OCSH__factory");
Object.defineProperty(exports, "OCSH__factory", { enumerable: true, get: function () { return OCSH__factory_1.OCSH__factory; } });
var SchemaRegistry__factory_1 = require("./SchemaRegistry__factory");
Object.defineProperty(exports, "SchemaRegistry__factory", { enumerable: true, get: function () { return SchemaRegistry__factory_1.SchemaRegistry__factory; } });
var Semver__factory_1 = require("./Semver__factory");
Object.defineProperty(exports, "Semver__factory", { enumerable: true, get: function () { return Semver__factory_1.Semver__factory; } });
