// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface OCSHLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "OCSHLib";
  readonly sourceName: "contracts/OSCHLib.sol";
  readonly abi: [{"inputs":[],"name":"ALLIANCE_LEADER_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"GAME_ADMIN_ROLE","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x60d4610034600b8282823980515f1a60731461002857634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c806317282d5c146040578063be22d27d146078575b5f80fd5b60667f828a9190dc16dc0116154c184677dac8abebc0b3aeeba46f3ba5f89b8e41439881565b60405190815260200160405180910390f35b60667f9b7946abd96dccbe6cfc6cc2c13300ab429d93e16fa72dc459eeccda73817f088156fea26469706673582212206964ff9ef2cbd7e5b4fce3d95fd1fd17f27fbbe3138a647ae94b9ac745379dca64736f6c63430008150033";
  readonly deployedBytecode: "0x7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c806317282d5c146040578063be22d27d146078575b5f80fd5b60667f828a9190dc16dc0116154c184677dac8abebc0b3aeeba46f3ba5f89b8e41439881565b60405190815260200160405180910390f35b60667f9b7946abd96dccbe6cfc6cc2c13300ab429d93e16fa72dc459eeccda73817f088156fea26469706673582212206964ff9ef2cbd7e5b4fce3d95fd1fd17f27fbbe3138a647ae94b9ac745379dca64736f6c63430008150033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/OSCHLib.sol";
  readonly buildInfoId: "solc-0_8_21-faeec72ec7ff8bc64f3840dcabd8f2bba9d6330c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["OCSHLib"]: OCSHLib$Type;
    ["contracts/OSCHLib.sol:OCSHLib"]: OCSHLib$Type;
  }
}