"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OCSHLib__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var OCSHLib__factory_1 = require("./OCSHLib__factory");
Object.defineProperty(exports, "OCSHLib__factory", { enumerable: true, get: function () { return OCSHLib__factory_1.OCSHLib__factory; } });
