/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oschLibSol from "./OSCHLib.sol";
export type { oschLibSol };
export type { OCSH } from "./OCSH";
export * as factories from "./factories";
export { OCSH__factory } from "./factories/OCSH__factory";
export type { OCSHLib } from "./OSCHLib.sol/OCSHLib";
export { OCSHLib__factory } from "./factories/OSCHLib.sol/OCSHLib__factory";
